export const TOPIC_TERMS = [
  // Core disease terms
  'lung cancer',
  'lung neoplasms',
  'NSCLC',
  'SCLC',
  'non-small cell lung',
  'small cell lung',
  'mesothelioma',
  'thoracic oncology',
  'thoracic neoplasms',
  'thymoma',
  'thymic carcinoma',
  'lung adenocarcinoma',
  'lung squamous cell carcinoma',
  'pleural mesothelioma',
  'large cell lung',
  'carcinoid lung',
  'pancoast',
  // Biomarkers & molecular targets
  'EGFR mutation',
  'EGFR exon',
  'ALK rearrangement',
  'ALK fusion',
  'ALK-positive',
  'ROS1',
  'KRAS G12C',
  'BRAF V600E lung',
  'MET exon 14',
  'MET amplification',
  'RET fusion',
  'NTRK fusion',
  'HER2 lung',
  'PD-L1',
  'TMB lung',
  'STK11',
  'KEAP1',
  'TP53 lung',
  'ctDNA lung',
  'liquid biopsy lung',
  // Drugs predominantly used in thoracic oncology
  'osimertinib',
  'sotorasib',
  'adagrasib',
  'amivantamab',
  'mobocertinib',
  'capmatinib',
  'tepotinib',
  'selpercatinib',
  'pralsetinib',
  'lorlatinib',
  'alectinib',
  'crizotinib',
  'brigatinib',
  'entrectinib',
  'lazertinib',
  'datopotamab deruxtecan',
  'trastuzumab deruxtecan lung',
  'sacituzumab govitecan lung',
  // Immunotherapy in lung
  'pembrolizumab lung',
  'nivolumab lung',
  'atezolizumab lung',
  'durvalumab lung',
  'ipilimumab lung',
  'tremelimumab lung',
  'cemiplimab lung',
  'sugemalimab',
  'tislelizumab lung',
  'serplulimab',
  // Chemotherapy regimens
  'carboplatin pemetrexed',
  'cisplatin etoposide',
  'cisplatin pemetrexed',
  'docetaxel lung',
  'gemcitabine lung',
  // Staging, screening & procedures
  'lung cancer screening',
  'low-dose CT screening',
  'LDCT screening',
  'pulmonary nodule',
  'lung nodule',
  'mediastinal staging',
  'EBUS',
  'endobronchial ultrasound',
  'lobectomy',
  'pneumonectomy',
  'VATS lung',
  'thoracoscopy',
  'sublobar resection',
  // Radiation
  'SBRT lung',
  'stereotactic body radiation lung',
  'thoracic radiotherapy',
  'concurrent chemoradiation lung',
  'prophylactic cranial irradiation',
  // Clinical settings
  'stage III lung',
  'stage IV lung',
  'locally advanced lung',
  'metastatic lung cancer',
  'early stage lung cancer',
  'neoadjuvant lung',
  'adjuvant lung',
  'perioperative lung',
  'brain metastases lung',
  'oligometastatic lung',
];

export const ACUTE_ONCOLOGY_TERMS = [
  // Oncologic emergencies
  'oncologic emergency',
  'oncological emergency',
  'acute oncology',
  'febrile neutropenia',
  'neutropenic sepsis',
  'neutropenic fever',
  'tumour lysis syndrome',
  'tumor lysis syndrome',
  'superior vena cava syndrome',
  'spinal cord compression',
  'malignant hypercalcemia',
  'hypercalcemia of malignancy',
  'malignant bowel obstruction',
  'malignant pericardial effusion',
  'malignant pleural effusion',
  'cardiac tamponade cancer',
  'raised intracranial pressure',
  'brain metastases',
  // Immunotherapy toxicity — irAEs
  'immune-related adverse events',
  'irAE',
  'irAEs',
  'immune checkpoint inhibitor toxicity',
  'checkpoint inhibitor adverse',
  'cytokine release syndrome',
  'immune-mediated colitis',
  'immune-mediated hepatitis',
  'immune-mediated pneumonitis',
  'immune-mediated nephritis',
  'immune-mediated endocrinopathy',
  'immune-mediated dermatitis',
  'immune-mediated myositis',
  'immune-mediated encephalitis',
  'immune-mediated arthritis',
  'myocarditis immunotherapy',
  'checkpoint inhibitor pneumonitis',
  'immunotherapy-related',
  'immunotherapy toxicity',
  'immunotherapy-induced thyroiditis',
  'immunotherapy-induced adrenal insufficiency',
  'immunotherapy-induced hypophysitis',
  'immunotherapy-induced diabetes',
  'immune-mediated myocarditis',
  'nivolumab toxicity',
  'pembrolizumab toxicity',
  'ipilimumab toxicity',
  'atezolizumab toxicity',
  'durvalumab toxicity',
  'steroid management irAE',
  'immunosuppression irAE',
  'infliximab irAE',
  'mycophenolate irAE',
  'ICI rechallenge',
  'checkpoint inhibitor rechallenge',
  'immune toxicity grading',
  'CTCAE immune',
  // Chemotherapy toxicity
  'chemotherapy toxicity',
  'extravasation',
  'mucositis',
  'pancytopenia',
  'thrombocytopenia chemotherapy',
  // Thrombosis & haematological
  'cancer-associated thrombosis',
  'venous thromboembolism cancer',
  'pulmonary embolism cancer',
  'disseminated intravascular coagulation',
  // Supportive care (acute, not palliative)
  'oncology supportive care',
  'antiemetic',
  'G-CSF',
  'granulocyte colony-stimulating factor',
  // Acute presentations
  'sepsis cancer',
  'acute kidney injury cancer',
  'hyponatremia cancer',
  'pathological fracture',
];
